language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t richg/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true richg/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-099861491961"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
